name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        name: Set up Zig
      - name: Verify Zig installation
        run: zig version
      - name: Verify Zig cc
        run: cc --version
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache Konan
        uses: actions/cache@v4
        with:
          enableCrossOsArchive: true
          key: ${{ runner.os }}-gradle-konan
          path: |
            ~/.konan
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.gradle_encryption_key }} # openssl rand -base64 16
          validate-wrappers: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          gradle-version: wrapper
      - name: Prepare directory
        run: mkdir -p linux_spawn_helper/build-x64
      - name: Run Build
        run: ./gradlew build --stacktrace
      - name: Upload build reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports-${{ matrix.os }}
          path: files/build/reports
          if-no-files-found: warn
